# Site settings
title: Murphy-PML

email: "hj.chung@kaist.ac.kr"
url: "http://hj-harry.github.io"
github_url: "http://github.com/hj-harry"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/hj-harry"
baseurl: "/Murphy_PML"
disqus_shortname: hj-harry

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
